### ISSUE TITLE
Hide "Watched"

### ISSUE THREAD

**Issue by JimmytheSquid** [allejok96/plugin.video.jwb-unofficial#12]
I am pretty sure there is no way to do this (because it is connecting to live website), but could there be a way to hide "watched" programs in this addon? Right now it puts a check mark beside them (very nice), but does not hide them. 
thanks

**Comment by allejok96** [comment]
Hey, sorry for the late reply. Kodi has this feature when browsing Movies and TV shows (in the left side menu), but apparently not in plugins. I'm pretty sure the plugin *could* check which files are watched and hide them, but I think this feature is up to the Kodi team to add.
