### ISSUE TITLE
[Feature request] Global search

### ISSUE THREAD

**Issue by mroova** [allejok96/plugin.video.jwb-unofficial#2]
Hello :)
thank You for continuing work on this great add-on.
Would it be possible to add search function for all the videos from tv.jw.org?
AFAIK, as of now it's only possible to search within a specific sub-category.
All the best :)

**Comment by allejok96** [comment]
This is a tricky one as it seems to require some form of authentication token ("JWT" to be exact). I'll have to dig into how that works a little bit more...

**Comment by mroova** [comment]
I don't know if it'll help at all, but I found Tidal addon for Kodi which supports global search:
https://github.com/arnesongit/plugin.audio.tidal2

**Comment by allejok96** [comment]
No, I'm afraid the problem is not how to do search in Kodi. It has more to do with the communication with the jw.org website, and it seems Tidal is doing a different thing... But thanks anyway.

**Comment by allejok96** [comment]
Hey seems like I had this commit lying around for a month, sorry bout that.
Hope you enjoy the new feature  :smiley: (and that it works)

**Comment by mroova** [comment]
Thank You so much :)
Works perfectly :)
