### ISSUE TITLE
[Feature request] Featured videos

### ISSUE THREAD

**Issue by mroova** [allejok96/plugin.video.jwb-unofficial#3]
Is there a chance of adding access to "featured videos" from the main website, just as it's already possible in each category?

**Comment by allejok96** [comment]
Thanks for pointing this out. It should be added and working now, easy fix. They must have made changes to the API, haven't seen that being possible before...

**Comment by mroova** [comment]
Thank You :)
My parents are going to be delighted :)
And to be honest, for more nerdy people it's also a great update :)
