### ISSUE TITLE
[Feature Request] Language Filter

### ISSUE THREAD

**Issue by howudodat** [allejok96/plugin.video.jwb-unofficial#4]
We speak 4 languages in the house, so the language we watch in is always changing.  Scrolling through all the entries in <set language> is cumbersome.  Would it be possible to add a Language Filter to the preferences such that we could do something like: e/fr/cr ... and then in the <set language> it filters only for matching languages?  Or simply add 2 options to preferences: language choices and language

**Comment by ca0abinary** [comment]
@howudodat Would an approach where the 5 most recently selected languages are placed at the top of the list suit your needs?

**Comment by allejok96** [comment]
Nice to see you around @ca0abinary. I've been thinking about this, but haven't found the time yet...

That feature would be a big improvement. But even nicer would be if we could get a "Watch in another language" to the context menu of each video. And in that menu we add let's say the 5 latest languages. To top it of we could have a "more languages..." at the bottom, but I have no idea how that would be done...

**Comment by howudodat** [comment]
> @howudodat Would an approach where the 5 most recently selected languages are placed at the top of the list suit your needs?

this would work just fine  for me.  Anything to shorten the time it takes to scroll through 200 languages.

The context menu is a good idea too

**Comment by allejok96** [comment]
Ok, so luckily I was sick for a week and had some days in the couch with the laptop :) I've pushed out a big big update, so we'll see how long it goes before new issues comes dropping in. All testing was made on v18 Leia.

Just so you know @howudodat, global language setting is now moved to the add-on's settings, so you can access it by pressing left while in the add-on. But now you can also select language for each video.

Also have a look at the README for new installation instructions to receive future updates automatically. Please report if anything is broken, as I'm kind of new to all of this.
