### ISSUE TITLE
Chain the songs instead of playing one by one

### ISSUE THREAD

**Issue by dvdbaro** [allejok96/plugin.video.jwb-unofficial#6]
Add-on version : 1.11.3
OS : LibreElec 9.1.501
Platform : RaspBerry Pi 4

Hi,
Would it be possible to chain the reading of the songs instead of having to selec them one by one ?

Thanks for your help
David

**Comment by allejok96** [comment]
I think Kodi 18 has built in Play from here if you open context menu

**Comment by dvdbaro** [comment]
You're right. Thanks

David
