### ISSUE TITLE
Kodi 19

### ISSUE THREAD

**Issue by AndrewChqng** [allejok96/plugin.video.jwb-unofficial#9]
Hi, really appreciate this add-on. Just wanted to ask if Kodi 19 support is there or if it's a possibility?

**Comment by allejok96** [comment]
Yes, there is Kodi 19 support

**Comment by AndrewChqng** [comment]
Oh yeah, should have checked 🤦‍♂️ thanks

**Comment by AndrewChqng** [comment]
Oh yeah, should have checked 🤦‍♂️ thanks

**Comment by allejok96** [comment]
No problem, just leave a message if you run into trouble :)
